import { v4 as uuidv4 } from "uuid";

const beverageItems = [
  {
    id: uuidv4(),
    name: "Lemonade",
    price: 25,
    description: "Lemonade made of rescued fruit",
    image: "Lemonade",
    weight: "1 BOOTLE 270 ML",
    carb: "75 KCAL",
    quantity: 1,
    uid: "",
  },
  {
    id: uuidv4(),
    name: "Blood Orange",
    price: 25,
    description: "Juice made of rescued fruit",
    image: "Juice_Blood_Orange",
    weight: "1 BOOTLE 270 ML",
    carb: "140 KCAL",
    quantity: 1,
    uid: "",
  },
  {
    id: uuidv4(),
    name: "Apple & Ginger",
    price: 25,
    description: "Juice made of rescued fruit",
    image: "Juice_Apple",
    weight: "1 BOOTLE 270 ML",
    carb: "140 KCAL",
    quantity: 1,
    uid: "",
  },
  {
    id: uuidv4(),
    name: "Kombucha",
    price: 25,
    description: "Organic kombucha from Malmö",
    image: "Kombucha",
    weight: "1 BOOTLE 330 ML",
    carb: "60 KCAL",
    quantity: 1,
    uid: "",
  },
  {
    id: uuidv4(),
    name: "Spring Water",
    price: 25,
    description: "Natural mineral water",
    image: "Sparkling_Water",
    weight: "1 BOOTLE 330 ML",
    carb: "0 KCAL",
    quantity: 1,
    uid: "",
  },
  {
    id: uuidv4(),
    name: "Fritz-Kola",
    price: 25,
    description: "Independent cola from Germany",
    image: "Fritz_Kola",
    weight: "1 BOOTLE 330 ML",
    carb: "130 KCAL",
    quantity: 1,
    uid: "",
  },
];

export default beverageItems;