import { v4 as uuidv4 } from "uuid";

const extrasItems = [
  {
    id: uuidv4(),
    name: "The Cheesy One",
    price: 15,
    weight: "70 G ",
    carb: "/ 15 SEK / 130 KCAL",
    image: "The_Cheesy_One",
    description: "with parmesan and mozzarella",
    imagepopup: "The_Cheesy_One_Popup",
    quantity: 1,
    uid: "",
  },
  {
    id: uuidv4(),
    name: "No Vampires",
    price: 15,
    weight: "/ 15 SEK / 70 G ",
    carb: "110 KCAL",
    image: "Hold_Back_Vampire",
    description: "with fresh garlic",
    quantity: 1,
    uid: "",
  },
  {
    id: uuidv4(),
    name: "Going nuts",
    price: 15,
    weight: "70 G ",
    carb: "/ 15 SEK / 110 KCAL",
    image: "Going_nuts",
    description: "with hazelnuts and raisin",
    quantity: 1,
    uid: "",
  },
  {
    id: uuidv4(),
    name: "Love in Lavain",
    price: 15,
    weight: "70 G ",
    carb: "/ 15 SEK / 110 KCAL",
    image: "Love_in_Lavain",
    description: "baked on our sourdough",
    quantity: 1,
    uid: "",
  },
  {
    id: uuidv4(),
    name: "The Baguette",
    price: 15,
    weight: "70 G ",
    carb: "/ 15 SEK / 110 KCAL",
    image: "As_Good_As_It_Baguettes",
    description: "As good as it Baguettes",
    quantity: 1,
    uid: "",
  },
  {
    id: uuidv4(),
    name: "Whipped butter",
    price: 15,
    weight: "30 G ",
    carb: "/ 15 SEK / 240 KCAL",
    image: "Whipped_Butter",
    description: "With sea salt and hint of lemon",
    quantity: 1,
    uid: "",
  },
  {
    id: uuidv4(),
    name: "Beet Hummus",
    price: 15,
    weight: "70 G ",
    carb: "/ 15 SEK / 119 KCAL",
    image: "Beetroot_Hummus",
    description: "with sea salt and hint of lemon",
    quantity: 1,
    uid: "",
  },
  {
    id: uuidv4(),
    name: "Truffle Aioli",
    price: 15,
    weight: "70 G ",
    carb: "/ 15 SEK / 204 KCAL",
    image: "Truffle_Aioli",
    description: "Aioli with taste of truffle",
    quantity: 1,
    uid: "",
  },
  {
    id: uuidv4(),
    name: "Sliced Avocado",
    price: 15,
    weight: "70 G ",
    carb: "/ 15 SEK / 105 KCAL",
    image: "Sliced_Avocado",
    quantity: 1,
    uid: "",
  },
  {
    id: uuidv4(),
    name: "US Pancakes",
    price: 15,
    description: "with lemon and blueberrys",
    image: "American_Pancakes",
    weight: "1 PIECE ",
    carb: "/ 15 SEK / 130 KCAL",
    quantity: 1,
    uid: "",
  },
  {
    id: uuidv4(),
    name: "Pancakes",
    price: 15,
    description: "with cream and jam",
    image: "Pancakes",
    weight: "1 PIECE ",
    carb: "/ 15 SEK / 130 KCAL",
    quantity: 1,
    uid: "",
  },
];

export default extrasItems;
