import { v4 as uuidv4 } from "uuid";

const soupItems = [
  {
    id: uuidv4(),
    name: "The Healing",
    price: 50,
    description: "Butternut squash, Red onions, Garlic, Coconut milk",
    image: "The Healing",
    weight: "1 PORTION 300 G",
    carb: "240 KCAL",
    quantity: 1,
    uid: "",
    removedItems: "",
  },
  {
    id: uuidv4(),
    name: "So Long Cold",
    price: 50,
    description: "Parsnips, Rosted garlic, Lemon, Maple syrup, Coconut milk",
    image: "So Long Cold",
    weight: "1 PORTION 300 G",
    carb: "240 KCAL",
    quantity: 1,
    uid: "",
    removedItems: "",
  },
  {
    id: uuidv4(),
    name: "Chilli Billie",
    price: 50,
    description: "Carrots, Chilli flakes, Peanuts, Sweet potato, Coconut milk ",
    image: "Chilli Billie",
    weight: "1 PORTION 300 G",
    carb: "240 KCAL",
    quantity: 1,
    uid: "",
    removedItems: "",
  },
  {
    id: uuidv4(),
    name: "Miss Muscle",
    price: 50,
    description: "Green peas, Coriander, Green chilli, Lime, Coconut milk",
    image: "Miss Muscle",
    weight: "1 PORTION 300 G",
    carb: "240 KCAL",
    quantity: 1,
    uid: "",
    removedItems: "",
  },
  {
    id: uuidv4(),
    name: "Low Carb",
    price: 50,
    description: "Sweet potato, Ginger, Cummin marsala, Garlic, Coconut milk",
    image: "Low Carb Good Mood",
    weight: "1 PORTION 300 G",
    carb: "240 KCAL",
    quantity: 1,
    uid: "",
    removedItems: "",
  },
];
  export default soupItems;